apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nodejs-no-dockerfile
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/cqi-tenant/nodejs-no-dockerfile/nodejs-no-dockerfile@sha256:11debe18f1433e652871068d635c3009ec30787aeb8bbd9b9e6dcb380d5c55a7
        name: my-nodejs
        resources: {}
status: {}
