apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-no-dockerfile
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-no-dockerfile
    app.kubernetes.io/part-of: nodejs-no-dockerfile
  name: nodejs-no-dockerfile
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-no-dockerfile
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-no-dockerfile
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/cqi-tenant/nodejs-no-dockerfile/nodejs-no-dockerfile@sha256:11debe18f1433e652871068d635c3009ec30787aeb8bbd9b9e6dcb380d5c55a7
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
